sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host:
    port:
    database:
    username:
    password:
  file:
    upload-dir: E://MyProject//cqwm//nginx-1.20.2//html//sky//static
  wechat:
    appid:
    secret:
    mchid :
    mchserialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:

spring:
  redis:
    host: localhost
    port: 6379